[[redirects]]
  from = "/api/claude"
  to = "https://api.anthropic.com/v1/messages"
  status = 200
  force = true
  [redirects.headers]
    X-Api-Key = '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'
    anthropic-version = "2023-06-01"
    Content-Type = "application/json"
